name: Amate FE Deployment Automizer

on:
  push:
    branches:
      - "main"

jobs:
  fe-build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Git Checkout
        uses: actions/checkout@v4        
        
      -
        name: Vite Build
        run: |
          npm install
          npm run build
      -
        name: Create default.conf
        run: |
          cat <<EOF > default.conf
          server {
              listen 80;
              server_name localhost;

              root /app/dist;
              index index.html;

              location / {
                  try_files \$uri \$uri/ /index.html;
              }

              error_page 404 /index.html;
          }
          EOF
      
      - 
        name: Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Image Build & Push [FE]
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: ajoumate/amate-fe:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
